# Generated by Django 2.2.7 on 2019-12-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_sacedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SACEdb',
        ),
    ]
