# Generated by Django 2.2.7 on 2019-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0004_sacedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacedb',
            name='idalumno',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
