# Generated by Django 2.2.7 on 2019-12-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0005_auto_20191212_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacedb',
            name='idalumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Producto'),
        ),
    ]
