# Generated by Django 2.2.7 on 2019-12-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0006_auto_20191212_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SACEdb',
        ),
    ]
