# Generated by Django 2.2.7 on 2019-12-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cod_dep', models.CharField(help_text='Codigo del Departamento', max_length=2, unique=True)),
                ('descripcion', models.CharField(help_text='Descripcion del Departamento', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
