# Generated by Django 2.2.7 on 2019-12-09 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cod_mun', models.CharField(help_text='Codigo del Municipio', max_length=4, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción del Municipio', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'unique_together': {('departamento', 'descripcion')},
            },
        ),
    ]
