# Generated by Django 2.2.7 on 2019-12-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_municipio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='departamento',
        ),
        migrations.AddField(
            model_name='categoria',
            name='cod_depto',
            field=models.CharField(default=1, help_text='Codigo del Departamento', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Descripcion del Departamento', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
