# Generated by Django 2.2.7 on 2019-12-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_auto_20191209_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cod_depto',
        ),
    ]
