# Generated by Django 2.2.7 on 2019-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_categoria_codigop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigop',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
