# Generated by Django 2.2.7 on 2019-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_auto_20191209_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='codigom',
            field=models.CharField(default=2, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
