# Generated by Django 2.2.7 on 2019-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_subcategoria_codigom'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='centroeducativo',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigoce',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='edad',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(default=1, max_length=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='grado',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='idencargado',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='identidadext',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreencargado',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='origen',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='telefono',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
