# Generated by Django 2.2.7 on 2019-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_auto_20191211_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='periodoext',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
