# Generated by Django 2.2.7 on 2019-12-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_producto_periodoext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='centroeducativo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoce',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(help_text='Descripción del Producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='edad',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idencargado',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreencargado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='origen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='periodoext',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
