# Generated by Django 2.2.7 on 2019-12-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_auto_20191212_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='centroeducativo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigoce',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idencargado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='identidadext',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombreencargado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='periodoext',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='telefono',
        ),
    ]
