# Generated by Django 2.2.7 on 2019-12-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_auto_20191212_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='observaciones',
        ),
    ]
