# Generated by Django 2.2.7 on 2019-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_remove_producto_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
