# Generated by Django 2.2.7 on 2019-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_producto_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SACE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidadsace', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Detalle de Alumno',
                'verbose_name_plural': 'Detalles de Alumno',
            },
        ),
    ]
