# Generated by Django 2.2.7 on 2019-12-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_auto_20191215_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.SACE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(help_text='Descripción del Producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='identidadext',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
