# Generated by Django 2.2.7 on 2019-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0023_auto_20191215_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='sace',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
