# Generated by Django 2.2.7 on 2019-12-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0024_sace_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLESACE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('identidadsace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.SACE')),
            ],
            options={
                'verbose_name': 'Detalle de Alumno',
                'verbose_name_plural': 'Detalles de Alumno',
            },
        ),
    ]
