# Generated by Django 2.2.7 on 2019-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0025_detallesace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesace',
            old_name='descripcion',
            new_name='nombresace',
        ),
        migrations.AddField(
            model_name='detallesace',
            name='aldea',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='caserio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='codcentro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='departamento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='grado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='municipio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='nombrecentro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='periodo',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesace',
            name='telefono',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
