# Generated by Django 2.2.7 on 2019-12-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0026_auto_20191215_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSINREGISTRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('identidadext', models.CharField(max_length=13)),
                ('descripcion', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('edad', models.CharField(max_length=2)),
                ('grado', models.CharField(max_length=2)),
                ('centroeducativo', models.CharField(max_length=100)),
                ('codigoce', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('idencargado', models.CharField(max_length=13)),
                ('nombreencargado', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=200)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.SubCategoria')),
            ],
            options={
                'verbose_name_plural': 'ProductosSINREGISTROS',
            },
        ),
    ]
