# Generated by Django 2.2.7 on 2019-12-16 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0027_productosinregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoINTERNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centroeducativo', models.CharField(max_length=100)),
                ('codigoce', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('NNA', models.CharField(max_length=100)),
                ('PMTE', models.CharField(max_length=100)),
                ('CS', models.CharField(max_length=100)),
                ('TOTAL', models.CharField(max_length=100)),
                ('niveleducativo', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=2)),
                ('sexo', models.CharField(max_length=2)),
                ('genero', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=200)),
                ('identidadext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.SACE')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.SubCategoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
