# Generated by Django 2.2.7 on 2019-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0028_productointerno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productointerno',
            options={'verbose_name_plural': 'ProductosInternos'},
        ),
        migrations.AddField(
            model_name='productointerno',
            name='destino',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
