# Generated by Django 2.2.7 on 2019-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_auto_20191215_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='productointerno',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
