# Generated by Django 2.2.7 on 2019-12-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0031_remove_productointerno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productointerno',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
