# Generated by Django 2.1.1 on 2019-12-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0035_auto_20191221_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Categoria'),
        ),
    ]
