# Generated by Django 2.1.1 on 2019-12-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0038_auto_20191221_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Validado', 'Validado'), ('Pendiente', 'Pendiente')], default='Ingresado', help_text='Situación actual del Alumno', max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Validado', 'Validado'), ('Pendiente', 'Pendiente')], default='Ingresado', help_text='Situación actual del Alumno', max_length=40),
        ),
        migrations.AddField(
            model_name='productosinregistro',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Validado', 'Validado'), ('Pendiente', 'Pendiente')], default='Ingresado', help_text='Situación actual del Alumno', max_length=40),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Validado', 'Validado'), ('Pendiente', 'Pendiente')], default='Ingresado', help_text='Situación actual del Alumno', max_length=40),
        ),
    ]
