# Generated by Django 2.1.1 on 2019-12-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0040_auto_20191223_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='estado2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado2',
        ),
        migrations.RemoveField(
            model_name='productointerno',
            name='estado2',
        ),
        migrations.RemoveField(
            model_name='productosinregistro',
            name='estado2',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='estado2',
        ),
        migrations.AlterField(
            model_name='productointerno',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Validado', 'Validado'), ('Pendiente', 'Pendiente')], default='Ingresado', help_text='Situación actual del Alumno', max_length=40),
        ),
    ]
