# Generated by Django 2.1.1 on 2020-01-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0041_auto_20191223_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productointerno',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
