# Generated by Django 2.1.1 on 2020-01-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0044_auto_20200103_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='productosinregistro',
            name='estado',
            field=models.IntegerField(max_length=2),
        ),
    ]
