# Generated by Django 2.1.1 on 2020-01-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0045_auto_20200103_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesace',
            name='departamento_id',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
